"""
Script generator — converts a plot data dict into a self-contained Python file.

The generated script:
  1. Embeds all data as Python literals (no external data files needed).
  2. Reproduces the exact plot that the backend produced.
  3. Has clearly labelled SETTINGS sections so scientists can customise without
     reading the service source code.
  4. Is immediately runnable:  pip install matplotlib scipy numpy  →  python3 script.py

Every plot type gets its own _code_* function that knows how to translate the
generic data dict into the right matplotlib calls.  The router passes the
PlotResult.data dict here after confirming format=script.
"""

import pprint
import textwrap


# ── Public entry point ────────────────────────────────────────────────────────

def generate_script(data: dict) -> str:
    """
    Generate a complete, runnable Python script from a plot data dict.

    Parameters
    ----------
    data : dict
        The PlotResult.data dict produced by any plot_* function.
        Must contain at minimum: plot_type, title, xlabel, ylabel,
        metadata, series, plot_options, figure_width, figure_height, dpi.

    Returns
    -------
    str
        The full Python source as a string.  The caller writes this to
        a Response with media_type="text/x-python".
    """
    plot_type    = data.get("plot_type", "tec_plot")
    title        = data.get("title", "TEC Plot")
    metadata     = data.get("metadata", {})
    series       = data.get("series", {})
    options      = data.get("plot_options", {})
    figure_width  = data.get("figure_width", 12.0)
    figure_height = data.get("figure_height", 6.0)
    dpi           = data.get("dpi", 100)
    xlabel        = data.get("xlabel", "Time, UT [h]")
    ylabel        = data.get("ylabel", "TEC, TECU")

    # Pretty-print Python literals — pprint gives readable multi-line output
    meta_repr   = pprint.pformat(metadata,   indent=4, width=88)
    series_repr = pprint.pformat(series,     indent=4, width=88)
    options_repr = pprint.pformat(options,   indent=4, width=88)

    # Pick the plot-type-specific body
    body = _route_plot_code(plot_type, series, options, xlabel, ylabel)

    return textwrap.dedent(f"""\
        #!/usr/bin/env python3
        \"\"\"
        {title}
        {'=' * min(len(title), 72)}
        Generated by TEC Analysis Backend

        Requirements: pip install matplotlib scipy numpy
        Run with:     python3 <this_file>.py
        \"\"\"

        import matplotlib.pyplot as plt
        import matplotlib.ticker as ticker
        import numpy as np

        # ── DATA ─────────────────────────────────────────────────────────────────────
        # All values from the backend computation — edit freely for post-processing.

        metadata = {meta_repr}

        series = {series_repr}

        plot_options = {options_repr}

        # ── SETTINGS — edit to customise the figure ───────────────────────────────
        TITLE         = {title!r}
        XLABEL        = {xlabel!r}
        YLABEL        = {ylabel!r}
        FIGURE_WIDTH  = {figure_width!r}   # inches
        FIGURE_HEIGHT = {figure_height!r}   # inches
        DPI           = {dpi!r}

        # ── PLOT CODE ─────────────────────────────────────────────────────────────
        fig, ax = plt.subplots(figsize=(FIGURE_WIDTH, FIGURE_HEIGHT), dpi=DPI)

        {_indent(body, 8)}

        ax.set_title(TITLE, fontsize=13)
        ax.set_xlabel(XLABEL, fontsize=13)
        ax.set_ylabel(YLABEL, fontsize=13)
        ax.xaxis.set_major_locator(ticker.MultipleLocator(2))
        ax.grid(True, which='major', color='#666666', linestyle='-', alpha=0.5)
        ax.minorticks_on()
        ax.grid(True, which='minor', color='#999999', linestyle='-', alpha=0.2)
        ax.legend(loc='upper left', fontsize=12)

        plt.tight_layout()
        plt.savefig('tec_plot.png', dpi=DPI, bbox_inches='tight')
        print('Saved: tec_plot.png')
        plt.show()
    """)


# ── Router ────────────────────────────────────────────────────────────────────

def _route_plot_code(
    plot_type: str, series: dict, options: dict, xlabel: str, ylabel: str
) -> str:
    """Return the plot-body code for the requested plot_type."""
    dispatch = {
        "absoltec_average":        _code_absoltec_average,
        "absoltec_single_day":     _code_single_day,
        "absoltec_multi_station":  _code_multi_station,
        "absoltec_per_station_avg": _code_absoltec_average,   # same shape
        "tec_satellite":           _code_tec_satellite,
        "tec_multi_satellite":     _code_tec_multi_satellite,
        "tec_sky_track":           _code_tec_sky_track,
    }
    fn = dispatch.get(plot_type, _code_generic)
    return fn(series, options)


# ── Plot-specific code generators ────────────────────────────────────────────

def _code_absoltec_average(series: dict, options: dict) -> str:
    show_ci  = options.get("show_student_ci", True)
    show_var = options.get("show_variance", False)

    lines = [
        "ut   = series['ut']",
        "mean = series['mean_tec']",
        "",
        "ax.plot(ut, mean, '--', label='average TEC')",
    ]
    if show_ci:
        lines += [
            "",
            "# Student-t confidence interval (half-width stored in student_ci)",
            "ci = series['student_ci']",
            "ax.errorbar(ut, mean, yerr=ci, fmt='.k', capsize=8,",
            "            label='Student CI', zorder=3)",
        ]
    if show_var:
        lines += [
            "",
            "var = series['variance']",
            "ax.errorbar(ut, mean, yerr=var, fmt='o', capsize=4,",
            "            label='variance', alpha=0.6, zorder=2)",
        ]
    return "\n".join(lines)


def _code_single_day(series: dict, options: dict) -> str:
    smooth = options.get("smooth", False)
    poly   = options.get("polynomial_order", 3)
    lines  = [
        "ut  = series['ut']",
        "tec = series['tec']",
        "",
    ]
    if smooth:
        lines += [
            "from scipy.signal import savgol_filter",
            f"poly   = {poly}",
            "window = max(poly + 2, len(tec) // 2 + 1)",
            "if window % 2 == 0: window += 1",
            "tec_s  = savgol_filter(tec, window, poly)",
            "",
            "ax.plot(ut, tec, alpha=0.35, color='steelblue', label='raw TEC')",
            "ax.plot(ut, tec_s, linewidth=2, color='steelblue', label='smoothed TEC')",
        ]
    else:
        lines += ["ax.plot(ut, tec, label='TEC')"]
    return "\n".join(lines)


def _code_multi_station(series: dict, options: dict) -> str:
    lines = [
        "# series is a dict: {station_code: {'ut': [...], 'tec': [...]}}",
        "for station, s in series.items():",
        "    ax.plot(s['ut'], s['tec'], label=station)",
    ]
    return "\n".join(lines)


def _code_tec_satellite(series: dict, options: dict) -> str:
    column = options.get("column", "tec_l1l2")
    lines = [
        "hour = series['hour']",
        f"tec  = series['{column}']",
        "",
        f"ax.plot(hour, tec, '.', markersize=3, label='{column}')",
    ]
    return "\n".join(lines)


def _code_tec_multi_satellite(series: dict, options: dict) -> str:
    column = options.get("column", "tec_l1l2")
    lines = [
        "# series is a dict: {satellite_code: {'hour': [...], 'tec_l1l2': [...]}}",
        "for sat, s in series.items():",
        f"    ax.plot(s['hour'], s['{column}'], '.', markersize=3,",
        "            label=sat, alpha=0.8)",
    ]
    return "\n".join(lines)


def _code_tec_sky_track(_series: dict, _options: dict) -> str:
    # Sky-track needs a polar axis — replace the default ax
    return textwrap.dedent("""\
        # Sky track needs a polar subplot — close the default one and create a new one.
        plt.close(fig)
        import numpy as np
        fig = plt.figure(figsize=(FIGURE_WIDTH, FIGURE_HEIGHT), dpi=DPI)
        ax  = fig.add_subplot(111, polar=True)
        ax.set_theta_zero_location('N')
        ax.set_theta_direction(-1)
        ax.set_ylim(0, 90)
        ax.set_yticks([10, 30, 50, 70, 90])
        ax.set_yticklabels(['80°', '60°', '40°', '20°', '0°'], fontsize=9)

        az     = np.radians(series['az_deg'])
        el_zen = np.array([90.0 - e for e in series['el_deg']])
        tec    = np.array(series['tec_l1l2'])

        sc = ax.scatter(az, el_zen, c=tec, s=6, cmap='plasma', alpha=0.85)
        cb = fig.colorbar(sc, ax=ax, pad=0.1, shrink=0.8)
        cb.set_label('TEC, TECU', fontsize=11)
        ax.set_title(TITLE, pad=18, fontsize=12)
    """)


def _code_generic(series: dict, _options: dict) -> str:
    """Fallback: plot whatever numeric 1D series we can find."""
    lines = ["# Generic fallback — adjust as needed"]
    for key, values in series.items():
        if isinstance(values, list) and values and isinstance(values[0], (int, float)):
            lines.append(f"ax.plot(series[{key!r}], label={key!r})")
    if len(lines) == 1:
        lines.append("pass  # no plottable series found")
    return "\n".join(lines)


# ── Utility ───────────────────────────────────────────────────────────────────

def _indent(code: str, spaces: int) -> str:
    """Re-indent a multi-line code block by 'spaces' spaces, preserving relative indentation."""
    prefix = " " * spaces
    # The block is already at 0 indentation; add prefix to every non-empty line
    lines = code.splitlines()
    result = []
    for i, line in enumerate(lines):
        if i == 0:
            result.append(line)           # first line sits inline after the prefix in the f-string
        else:
            result.append(prefix + line if line.strip() else "")
    return "\n".join(result)
